---
- name: Verify
  hosts: all
  tasks:

  # NOTE that verify.yml does not inherit values from your playbook in anyway, they are seperate playbooks and run seperately.
  - name: set some stuff
    set_fact:
      nginxconf: "/etc/nginx/sites-enabled"
      homedir: "{{ ansible_env.HOME }}"
      package_list_command: "pacman -Q"

  - name: set some more stuff
    set_fact:
      venvhome: "{{ homedir }}/.virtualenvs/neovim"

  - name: define packages, files, directories and other stuff you want to check lots of
    set_fact:
      required_files:
        - path: "{{ homedir }}/.config/nvim/airline.vim"
          isdir: false
        - path: "{{ homedir }}/.config/nvim/ale.vim"
          isdir: false
        - path: "{{ homedir }}/.config/nvim/deoplete.vim"
          isdir: false
        - path: "{{ homedir }}/.config/nvim/ftdetect"
          isdir: true
        - path: "{{ homedir }}/.config/nvim/init.vim"
          isdir: false
        - path: "{{ homedir }}/.config/nvim/plugins.vim"
          isdir: false
        - path: "{{ homedir }}/.config/nvim/yamllint.conf"
          isdir: false
      required_packages:
        - "neovim"
      required_pip_packages:
        - package: "powerline-status"
          venv: '{{ venvhome }}/bin/pip'
        - package: "pynvim"
          venv: '{{ venvhome }}/bin/pip'
#      required_services:
#      required_ports:
#
  - name: include the standard verifier
    include_tasks: verify_standard.yml

# Add role specific tests here
