---
# tasks file for geosword.neovim.
#
# install neovim
- name: install package neovim from the arch tree
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  loop: "{{ neovim_packages }}"

- name: create some folders for adding configuration / plugins
  file:
    path: "{{ dir.path }}"
    state: directory
    owner: "{{ dir.owner }}"
    group: "{{ dir.group }}"
    mode: "{{ dir.mode }}"
  loop: "{{ neovim_dirs }}"
  loop_control:
    label: path
    loop_var: dir

- name: install the python libraries via pip.
  pip:
    name:
      - powerline-status
      - pynvim
    virtualenv: "{{ neovim_virtual_env_dir }}"

- name: install neovim config
  synchronize:
    src: "files/"
    dest: "{{ neovim_config_dir }}/"

- name: run the Plugin install process in neovim
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ neovim_vimplug_dir }}"

# If you have anything like this that will report "changed" on a second run, then idempotence tests will fail. molecule-idempotence-notest prevents that from happening
# noqa 305 301 prevents ansible-lint from complaining about using shell and that shell will always report something changed. check ansible-lint -L for details

- name: install plugins and then quit # noqa 305 301
  shell:
    cmd: "nvim +PlugInstall +qall"
  tags:
    - molecule-idempotence-notest
